Authentication support, configurable max packet size
tg44/mqtt-prometheus-message-exporter pull request #2
Opened 2020-02-13 21:10 UTC by ginkel

This PR adds authentication support and configurable max packet size (as mqtt-prometheus-message-exporter was regularly crashing with the default 4k). I am not too happy with the explicit Option.isPresent checks, but am not too familiar with Scala to figure out a better way that is more idiomatic.

The exporter silently exits when the credentials are wrong, but I think it already did so before for wrong connection details.

Closes #1.

2020-02-14 14:41 UTC, tg44 requested changes
the max pocket size is missing from the example.conf

2020-02-14 14:41 UTC, tg44 commented on src/main/scala/xyz/tg44/prometheus/Main.scala
> +  appConf.mqtt.maxPacketSize.foreach(maxPacketSize =>
```
val mqttSessionSettings = appConf.mqtt.maxPacketSize.fold(MqttSessionSettings())(maxPacketSize => MqttSessionSettings().withMaxPacketSize(maxPacketSize))
```
or
```
val mqttSessionSettings = appConf.mqtt.maxPacketSize.map(MqttSessionSettings().withMaxPacketSize(maxPacketSize)).getOrElse(MqttSessionSettings())
```

2020-02-14 14:41 UTC, tg44 commented on src/main/scala/xyz/tg44/prometheus/Main.scala
> +  private val connect: Connect =
its kinda the same but a bit more tricky:
```
appConf.mqtt.username.flatMap(username => appConf.mqtt.password.map(password => Connect("prom-mqtt", ConnectFlags.CleanSession, username, password))).getOrElse(Connect("prom-mqtt", ConnectFlags.CleanSession))
```

2020-02-14 14:45 UTC, tg44 commented
Wow, I didn't noticed that this is crashing sometimes, but you are right... probably we should export some self metrics to make this more visible...

2020-02-14 14:48 UTC, tg44 commented
Ohh and also; can you upgrade the readme too, and add some thoughts about the optional authentication?

2020-02-16 13:08 UTC, merged

2020-02-16 14:27 UTC, ginkel commented
Thanks (and sorry that I didn't find time to implement your suggestions myself)!

2020-02-16 14:29 UTC, tg44 commented
No problem at all! I also added the uptime support.